name: Deploy to Dev ENV

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Install railways CLI
        run: npm install -g @railway/cli

      - name: Run Migration
        run: |
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          npx prisma migrate deploy
          
      - name: Deploy to railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}